parameters:
    # entities

    # services
    symfony2_economic.soap_api_service.class: Spoort\Bundle\Symfony2EconomicBundle\Services\SoapApi

services:
    symfony2_economic.soap_api_service:
        class: '%symfony2_economic.soap_api_service.class%'
        arguments:
            - symfony2_economic_config: '%symfony2_economic_config%'